-- CREATE DATABASE Customer_behavi
USE customer_behaviour;




--  Q1. What is the total revenue generated by male vs. female customers?
SELECT gender , sum(purchase_amount) as revenue
from customer_data
group by gender;

--  Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer_data
WHERE discount_applied = 'Yes'
  AND purchase_amount > (SELECT AVG(purchase_amount) FROM customer_data);

--  Q3. Which are the top 5 products with the highest average review rating?
SELECT  item_purchased,AVG(review_rating) as "average products rating"
from customer_data
group by item_purchased
order by AVG(review_rating) desc
limit 5;

--  Q4. Compare the average purchase amounts between Standard and Express shipping types.
SELECT shipping_type,
ROUND(AVG(purchase_amount),2)
from customer_data
where shipping_type in ('Standard','Express')
group by shipping_type;

-- ⭐ Q5. Do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers?
SELECT subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_spend
from customer_data
group by subscription_status
order by total_spend, avg_spend;


-- ⭐ Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    item_purchased,
    ROUND(
        SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/ COUNT(*) * 100.0,2) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- ⭐ Q7. Segment customers into New, Returning, and Loyal based on previous purchases.

-- ⭐ Q8. What are the top 3 most purchased products within each category?

-- ⭐ Q9. Are repeat buyers (more than 5 purchases) more likely to subscribe?

-- ⭐ Q10. What is the revenue contribution of each age group?
